### ISSUE TITLE
【Error】module 'asyncio' has no attribute 'run'.

### ISSUE THREAD

**Issue by luoshuijs** [xiaoqie/pybiliroku#3]
大佬你在`README.md`文档中标注python需要版本3.6+，当然我理解是包括3.6版本了hhh。
在我电脑上python3.6.6版本的，结果运行错误。
```python
Traceback (most recent call last):
  File "roku.py", line 139, in <module>
    asyncio.run(main())
AttributeError: module 'asyncio' has no attribute 'run'
```
`asyncio.run()`这个是Python3.7+的新方法。包括3.6以下版本是没有这个方法的，导致运行错误。
如果大佬愿意往下兼容，可以试试`asyncio.get_event_loop()`来执行异步事件。
```python
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
还有大佬可以创建一个`requirements.txt`，可以方便安装需要的模块。内容如下。
```
aiohttp
psutil
websockets
```
据我了解`websockets`模块并不是自带的，得安装。
一键安装模块的命令为`pip install -r requirements.txt`。

**Comment by xiaoqie** [comment]
README中标注有误，已修改。实际上在用pipenv管理依赖。
